### ISSUE TITLE
BUGS - Remove Method doesn't work 

### ISSUE THREAD

**Issue by SimonLXiong** [hbarton2/cscd350-f24-AndTheyWereRoomates#101]
![image](https://github.com/user-attachments/assets/672a6148-f91c-46e2-b800-cc7948bf1431)
![image](https://github.com/user-attachments/assets/04650a44-1824-4fec-a062-e031b774c65e)
![image](https://github.com/user-attachments/assets/5710ece3-c229-4c44-9433-2cd122438329)

In the Remove Method in UMLController, it adds method instead of removing. Change it from Remove to Add

**Comment by Delinquent-Pointer** [comment]
v3.3.72 New CLI
