### ISSUE TITLE
BUGS - Remove Parameter and Rename Parameter doesn't work 

### ISSUE THREAD

**Issue by SimonLXiong** [hbarton2/cscd350-f24-AndTheyWereRoomates#103]
![image](https://github.com/user-attachments/assets/94569d2c-ea6d-4b5a-ae6a-d229f73f3d55)
![image](https://github.com/user-attachments/assets/2deaa386-f17a-49eb-97e8-d154d1af2b1a)
![image](https://github.com/user-attachments/assets/24976a7a-7d95-4f1a-ab8a-d2f8b37148cd)

Removing Parameter returns a NullPointException error because hasMethod for some reason doesn't think the input method exists
This works for Add Parameter for some reason. 
Reason for crashing for Remove and Rename but not for Add is unclear. Maybe remove ``` && (method.getParameter().isEmpty())``` because it'll always return false because it's gonna have a method in order to work?

**Comment by Delinquent-Pointer** [comment]
v3.3.72 New CLI
