### ISSUE TITLE
BUGS - Loading files don't have catching/throwing

### ISSUE THREAD

**Issue by SimonLXiong** [hbarton2/cscd350-f24-AndTheyWereRoomates#126]
![image](https://github.com/user-attachments/assets/04c32515-5e53-4478-aa23-d70493b56496)
![image](https://github.com/user-attachments/assets/ff114770-6e19-479d-bf29-760cb023e975)
![image](https://github.com/user-attachments/assets/c24fe599-ec6b-4931-a58a-2f9bbc5d870a)

Loading files doesn't have error handling, displaying this if a file wasn't found in Menu class.
This doesn't crash the program

**Comment by Delinquent-Pointer** [comment]
v3.3.72 New CLI
