### ISSUE TITLE
BUGS - Rename Class mistake

### ISSUE THREAD

**Issue by SimonLXiong** [hbarton2/cscd350-f24-AndTheyWereRoomates#127]
![image](https://github.com/user-attachments/assets/86e2abcc-4a2a-4c5b-8774-4b539e04d200)
![image](https://github.com/user-attachments/assets/3e690a0b-9b45-43e1-87e0-9160fd51e00b)

Rename class only needs 3 inputs (rename class <new class name>) but it requires 4 inputs for, along with the array inputs swapped (the first input should be 2 not 3)

**Comment by Delinquent-Pointer** [comment]
v3.3.72 New CLI
