### ISSUE TITLE
FEATURE - Save diagram with position preserved GUI

### ISSUE THREAD

**Issue by anthonyOrth** [hbarton2/cscd350-f24-AndTheyWereRoomates#156]
●	As a user,
I want to save a diagram with the class box positions preserved,
So that when I load the file in either the CLI or GUI, the layout remains consistent and does not have overlapping boxes.

○	Given the user has saved work from a previous session,
When the user loads that work into GUI mode,
Then the classes should appear in the same positions they were saved in.

**Comment by Delinquent-Pointer** [comment]
Already done
