### ISSUE TITLE
FEATURE/Save-picture-without-ui-elements

### ISSUE THREAD

**Issue by anthonyOrth** [hbarton2/cscd350-f24-AndTheyWereRoomates#198]
As a user,
I want my saved picture not to contain any UI elements.
So that my UML diagram remains readable without unwanted icons.

Scenario:
Given the user has a UML diagram open in the GUI,
When the user selects the "Export" option,
Then the system generates a .png file containing the UML diagram without any UI elements,
And the file is saved in the specified location.

**Comment by Delinquent-Pointer** [comment]
Isn't this already in Feature/export image #209
