### ISSUE TITLE
FEATURE- SAVE in both CLI/GUI

### ISSUE THREAD

**Issue by ulises-aguilar** [hbarton2/cscd350-f24-AndTheyWereRoomates#200]
As a user,
I want the option to save my work both in CLI and GUI.
So that I can open my work in both interfaces, and both should be similar.
Scenario:
Given the user has a UML diagram saved on their machine,
When the user opens the file,
Then the diagram will load in their respective interfaces.

**Comment by Delinquent-Pointer** [comment]
Already Done
