### ISSUE TITLE
REFACTOR-DOCUMENTATIONS for the Whole Project

### ISSUE THREAD

**Issue by anthonyOrth** [hbarton2/cscd350-f24-AndTheyWereRoomates#204]
Updating the readme to the current status of the project for the cli.

**Comment by Delinquent-Pointer** [comment]
Ladies and gentlemen, everyone needs to make sure the project reflects the final version.

**Comment by Delinquent-Pointer** [comment]
- version number needs to be removed
- update how user can get our released version

**Comment by Delinquent-Pointer** [comment]
Updated readme file Completed some tests #238
