### ISSUE TITLE
BUGS - No Error Handling for commands in Menu

### ISSUE THREAD

**Issue by SimonLXiong** [hbarton2/cscd350-f24-AndTheyWereRoomates#99]
When inputting a command that's not the required length for the command, the program crashes.

![image](https://github.com/user-attachments/assets/bf30aa7e-3706-4802-831f-f21b55023906)
![image](https://github.com/user-attachments/assets/d78bf32c-f56c-4426-bba4-bf317e5a7966)

In the image above, adding Field requires a field name and a type but the program crashes if the command doesn't have the required number of entries.
We need to create an error handler for all entries otherwise the program crashes.

**Comment by Delinquent-Pointer** [comment]
v3.3.72 New CLI
